### ISSUE TITLE
VSO health "quad chart"

### ISSUE THREAD

**Issue by wafels** [aringlis/vso_health#12]
It might be useful to generate a VSO health "quad chart". The quad chart would show only those sources for which at least one client failed. This would enable quick understanding of which clients are failing for which sources. The chart would look something like what is shown in the attachment. I don't think we need to show the sources for which both clients work.

[health quad plot.pdf](https://github.com/aringlis/vso_health/files/11548556/health.quad.plot.pdf)

**Comment by aringlis** [comment]
VSO Health Quadrant Chart has been added.
